apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: demo
  labels:
    scenario: imagepull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: nginx:this-tag-does-not-exist
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: demo
spec:
  selector:
    app: checkout
  ports:
    - port: 80
      targetPort: 80
